# Generated by Django 3.0.7 on 2020-12-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orders_initiated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.CharField(max_length=32),
        ),
    ]
