# Generated by Django 3.0.7 on 2021-01-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20210102_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_number',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
