# Generated by Django 3.0.7 on 2021-01-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_orders_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
