# Generated by Django 3.0.7 on 2021-01-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20210109_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pay_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='sent_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='sent_tracking',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
