# Generated by Django 3.0.7 on 2021-03-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20210109_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_message',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
