# Generated by Django 3.0.7 on 2021-03-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_orders_order_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
